import { useRef } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SAMPLE_REPORT_HTML } from "@/data/sampleReport";

const SampleReport = () => {
  const iframeRef = useRef<HTMLIFrameElement>(null);

  const handleIframeLoad = () => {
    const iframe = iframeRef.current;
    if (!iframe) return;
    try {
      const doc = iframe.contentDocument || iframe.contentWindow?.document;
      if (doc) {
        const height = doc.documentElement.scrollHeight || doc.body.scrollHeight;
        iframe.style.height = `${height}px`;
      }
    } catch (e) {
      console.error("Failed to resize iframe:", e);
    }
  };

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />
      <main className="flex-1 pt-20 pb-12 px-4">
        <div className="container mx-auto max-w-5xl">
          <div className="mb-6 text-center">
            <h1 className="font-display text-2xl font-bold text-foreground mb-2">
              Sample Report
            </h1>
            <p className="text-sm text-muted-foreground">
              See exactly what you get — a real report generated by ScopeSG
            </p>
          </div>
          <div className="rounded-lg border border-border/50 overflow-hidden">
            <iframe
              ref={iframeRef}
              title="Sample Business Report"
              srcDoc={SAMPLE_REPORT_HTML}
              onLoad={handleIframeLoad}
              sandbox="allow-same-origin allow-scripts"
              style={{ width: "100%", minHeight: "800px", border: "none", display: "block" }}
            />
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default SampleReport;