import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const REPORT_PROMPT = `You are a senior business consultant preparing a PREMIUM Business Viability Report for a client looking to start a business in Singapore. The current date is ${new Date().toISOString().split('T')[0]}.

Based on the consultation conversation provided, generate a comprehensive, professional report in **Markdown format** with the following sections:

# Premium Business Viability Report — [Business Name/Type]
## Prepared by ScopeSG • [Current Date]

---

### Executive Summary
A concise 3-4 paragraph overview of the business opportunity, key findings, and overall recommendation.

### 1. Market Analysis
- Market size and growth rate (cite sources like DOS, MTI, or industry reports)
- Key market drivers and trends in Singapore
- Target market segmentation and sizing
- Consumer behaviour patterns relevant to this business

### 2. Competitive Landscape
- Top 5-10 existing competitors in Singapore
- Competitive advantages and differentiators needed
- Market positioning strategy recommendation
- SWOT analysis (table format)

### 3. Financial Projections
**Startup Costs Breakdown:**
| Category | Estimated Cost (SGD) |
|----------|---------------------|
| Registration & Licensing | $X |
| Premises / Setup | $X |
| Equipment & Technology | $X |
| Initial Inventory | $X |
| Marketing Budget (3 months) | $X |
| Working Capital (6 months) | $X |
| Contingency (15%) | $X |
| **Total** | **$X** |

**Revenue Projections:**
| Metric | Conservative | Moderate | Optimistic |
|--------|-------------|----------|-----------|
| Monthly Revenue (Month 6) | $X | $X | $X |
| Monthly Revenue (Month 12) | $X | $X | $X |
| Break-even Timeline | X months | X months | X months |
| Year 1 Profit/Loss | $X | $X | $X |

### 4. Regulatory & Compliance Guide
- Complete list of required licenses and permits
- Step-by-step registration process with ACRA
- Industry-specific regulations (SFA, NEA, MAS, etc.)
- PDPA compliance requirements
- Employment regulations if hiring staff
- GST registration requirements and thresholds
- Estimated timeline for all approvals

### 5. Risk Assessment & Mitigation
| Risk | Likelihood | Impact | Mitigation Strategy |
|------|-----------|--------|-------------------|
| [Risk 1] | High/Med/Low | High/Med/Low | [Strategy] |
| ... | ... | ... | ... |

### 6. Government Grants & Support
- Applicable grants (EDG, MRA, Startup SG, PSG, etc.)
- Eligibility criteria for each
- Application process and timeline
- Estimated funding available

### 7. 90-Day Launch Plan
**Week 1-2:** [Actions]
**Week 3-4:** [Actions]
**Month 2:** [Actions]
**Month 3:** [Actions]

### 8. Key Success Factors
Top 5 critical success factors with actionable recommendations.

---

**Disclaimer:** This report is generated using AI-powered analysis and publicly available data. It is for informational purposes only and does not constitute financial, legal, or professional advice. Business outcomes depend on execution, market conditions, and factors beyond projections. Consult qualified professionals before making business decisions. Sources cited are indicative; verify all regulatory requirements with the relevant Singapore government agencies.

---
*Report generated by ScopeSG • www.scopesg.com*

IMPORTANT:
- All monetary values must be in SGD
- Be specific to Singapore's context, laws, and market conditions
- Cite relevant Singapore government agencies and programmes
- Use realistic, data-grounded estimates
- Format as clean, professional Markdown`;

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    // Authenticate user
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? ""
    );
    const authHeader = req.headers.get("Authorization")!;
    const token = authHeader.replace("Bearer ", "");
    const { data: userData } = await supabaseClient.auth.getUser(token);
    const user = userData.user;
    if (!user) throw new Error("User not authenticated");

    const { orderId } = await req.json();
    if (!orderId) throw new Error("orderId is required");

    // Fetch order
    const { data: order, error: orderError } = await supabaseAdmin
      .from("report_orders")
      .select("*")
      .eq("id", orderId)
      .eq("user_id", user.id)
      .single();

    if (orderError || !order) throw new Error("Order not found");
    if (order.status === "completed" && order.report_content) {
      return new Response(JSON.stringify({ report: order.report_content }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Build conversation context from consultation data
    const consultationMessages = order.consultation_data as Array<{ role: string; content: string }>;
    const conversationSummary = consultationMessages
      .map((m: { role: string; content: string }) => `${m.role === "user" ? "Client" : "Consultant"}: ${m.content}`)
      .join("\n\n");

    // Generate report via AI
    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: REPORT_PROMPT },
          {
            role: "user",
            content: `Here is the consultation conversation with the client:\n\n${conversationSummary}\n\nGenerate the full Premium Business Viability Report based on this consultation.`,
          },
        ],
      }),
    });

    if (!response.ok) {
      const text = await response.text();
      console.error("AI gateway error:", response.status, text);
      throw new Error("Failed to generate report");
    }

    const aiResult = await response.json();
    const reportContent = aiResult.choices?.[0]?.message?.content;
    if (!reportContent) throw new Error("No report content generated");

    // Save report
    await supabaseAdmin
      .from("report_orders")
      .update({ status: "completed", report_content: reportContent })
      .eq("id", orderId);

    return new Response(JSON.stringify({ report: reportContent }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("generate-report error:", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
